// Block environment validation core (NODE shared infra, design §7.1 and the FROZEN
// wire contract protocol/v1/wire.schema.json $defs.blockEnv). Node-agnostic: it
// enforces the wire shape and the consistency invariants that need NO node state,
// and it explicitly DEFERS the checks that require the node (base_fee/blob
// derivation from the parent + fork rules, fork_rules_digest generation, parent
// existence, gas_limit vs. parent rules). It never fabricates a deferred check.
//
// Honesty red lines (design §7.1):
//   - author must be explicit and non-zero: a candidate has no real seal, so we must
//     NOT let a failed Author extraction silently become the zero address.
//   - base_fee / blob fields are OPTIONAL and, when present, are validated for shape
//     only here; their DERIVATION from parent+fork rules is the adapter's job and is
//     not accepted as an arbitrary zero to bypass (the adapter recomputes them).
//   - optional fields absent => absent (omitted), never faked with zero.
//   - timestamp_ms and timestamp_seconds must be consistent for this fork's ms/s
//     encoding: timestamp_ms / 1000 == timestamp_seconds (BSC MilliTimestamp).
//   - fork_rules_digest is generated by the node from chainConfig/number/time and
//     echoed; the pure core only checks it is a well-formed hash32, never its value.
package arb

import (
	"errors"
	"fmt"
	"strconv"
)

// zeroAddress is the canonical wire form of the zero address.
const zeroAddress = "0x0000000000000000000000000000000000000000"

// BlockEnv mirrors the frozen wire blockEnv (protocol/v1/wire.schema.json). Integers
// are strict decimal strings; hashes/addresses lowercase 0x-hex; extra_data is
// even-length hex (rawtx). The four optional fields are pointers with omitempty so
// an absent value is OMITTED (not zero) on the wire.
type BlockEnv struct {
	Number           string `json:"number"`
	ParentHash       string `json:"parent_hash"`
	TimestampMs      string `json:"timestamp_ms"`
	TimestampSeconds string `json:"timestamp_seconds"`
	Author           string `json:"author"`
	GasLimit         string `json:"gas_limit"`
	Difficulty       string `json:"difficulty"`
	MixDigest        string `json:"mix_digest"`
	ExtraData        string `json:"extra_data"`
	ForkRulesDigest  string `json:"fork_rules_digest"`

	// Optional: absent => nil => omitted (never zero-faked, design §7.1).
	BaseFee          *string `json:"base_fee,omitempty"`
	BlobGasUsed      *string `json:"blob_gas_used,omitempty"`
	ExcessBlobGas    *string `json:"excess_blob_gas,omitempty"`
	ParentBeaconRoot *string `json:"parent_beacon_root,omitempty"`
}

// Errors surfaced by block-env validation. Pattern/shape failures wrap
// ErrBlockEnvBadField (errors.Is-checkable) with the field name for context; the
// semantic invariants have their own sentinels.
var (
	ErrBlockEnvBadField  = errors.New("arb: block_env field malformed")
	ErrZeroAuthor        = errors.New("arb: block_env author must be explicit non-zero (no silent zero author)")
	ErrTimestampMismatch = errors.New("arb: block_env timestamp_ms/1000 must equal timestamp_seconds")
	ErrZeroNumber        = errors.New("arb: block_env number must be >= 1 (target = parent+1)")
	ErrZeroGasLimit      = errors.New("arb: block_env gas_limit must be > 0")
)

// ValidateBlockEnv enforces the wire shape and node-independent consistency of env.
// It returns the FIRST problem found, or nil if the env is well-formed and
// internally consistent. A nil return does NOT mean the env is fully accepted: the
// adapter must still recompute/verify base_fee, blob fields, fork_rules_digest, and
// parent linkage against the node (see file header) — those are deliberately not
// faked here.
func ValidateBlockEnv(env BlockEnv) error {
	// Required decimal-string uints.
	for _, f := range []struct {
		name string
		val  string
	}{
		{"number", env.Number},
		{"timestamp_ms", env.TimestampMs},
		{"timestamp_seconds", env.TimestampSeconds},
		{"gas_limit", env.GasLimit},
		{"difficulty", env.Difficulty},
	} {
		if !isUintStr(f.val) {
			return fmt.Errorf("%w: %s", ErrBlockEnvBadField, f.name)
		}
	}

	// Required hashes / address / rawtx.
	if !isHash32(env.ParentHash) {
		return fmt.Errorf("%w: parent_hash", ErrBlockEnvBadField)
	}
	if !isHash32(env.MixDigest) {
		return fmt.Errorf("%w: mix_digest", ErrBlockEnvBadField)
	}
	if !isHash32(env.ForkRulesDigest) {
		return fmt.Errorf("%w: fork_rules_digest", ErrBlockEnvBadField)
	}
	if !isAddress(env.Author) {
		return fmt.Errorf("%w: author", ErrBlockEnvBadField)
	}
	if !isRawtxHex(env.ExtraData) {
		return fmt.Errorf("%w: extra_data", ErrBlockEnvBadField)
	}

	// Optional fields: when present must be valid; absence is legal.
	if env.BaseFee != nil && !isUintStr(*env.BaseFee) {
		return fmt.Errorf("%w: base_fee", ErrBlockEnvBadField)
	}
	if env.BlobGasUsed != nil && !isUintStr(*env.BlobGasUsed) {
		return fmt.Errorf("%w: blob_gas_used", ErrBlockEnvBadField)
	}
	if env.ExcessBlobGas != nil && !isUintStr(*env.ExcessBlobGas) {
		return fmt.Errorf("%w: excess_blob_gas", ErrBlockEnvBadField)
	}
	if env.ParentBeaconRoot != nil && !isHash32(*env.ParentBeaconRoot) {
		return fmt.Errorf("%w: parent_beacon_root", ErrBlockEnvBadField)
	}

	// Semantic invariants that need no node state.
	if env.Author == zeroAddress {
		return ErrZeroAuthor
	}
	if env.Number == "0" {
		return ErrZeroNumber
	}
	if env.GasLimit == "0" {
		return ErrZeroGasLimit
	}

	// timestamp_ms / 1000 == timestamp_seconds. Parse as uint64 (block timestamps
	// fit comfortably); a parse failure here is a malformed field.
	ms, err := strconv.ParseUint(env.TimestampMs, 10, 64)
	if err != nil {
		return fmt.Errorf("%w: timestamp_ms", ErrBlockEnvBadField)
	}
	sec, err := strconv.ParseUint(env.TimestampSeconds, 10, 64)
	if err != nil {
		return fmt.Errorf("%w: timestamp_seconds", ErrBlockEnvBadField)
	}
	if ms/1000 != sec {
		return ErrTimestampMismatch
	}

	return nil
}

// --- wire-type validators (shared; isID32/isHash32 share the 32-byte hex pattern) ---

// isHash32 matches ^0x[0-9a-f]{64}$ (same shape as id32).
func isHash32(s string) bool { return isID32(s) }

// isAddress matches ^0x[0-9a-f]{40}$.
func isAddress(s string) bool {
	if len(s) != 42 || s[0] != '0' || s[1] != 'x' {
		return false
	}
	return allLowerHex(s[2:])
}

// isUintStr matches ^(0|[1-9][0-9]*)$ — no +, no leading zeros, zero is "0".
func isUintStr(s string) bool {
	if s == "" {
		return false
	}
	if s == "0" {
		return true
	}
	if s[0] < '1' || s[0] > '9' {
		return false // leading zero or sign not allowed
	}
	for i := 1; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

// isRawtxHex matches ^0x([0-9a-f]{2})*$ — even-length lowercase hex, "0x" allowed
// (empty extra_data). BSC extra_data is not empty in practice, but the wire type
// permits an even-length hex string; emptiness is a node-rule concern, not shape.
func isRawtxHex(s string) bool {
	if len(s) < 2 || s[0] != '0' || s[1] != 'x' {
		return false
	}
	body := s[2:]
	if len(body)%2 != 0 {
		return false
	}
	return allLowerHex(body)
}

func allLowerHex(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return false
		}
	}
	return true
}
